---
# This playbook ensures all burp extensions are in place
- hosts: all
  vars:
    extension_directory: "{{ansible_env.HOME}}/burpExtensions"
    jython_version: "2.7.0"
    brew_deps:
      - 'ant'
      - 'phantomjs'
    xss_validator_directory: "{{extension_directory}}/xssValidator"
    xss_validator_extender_directory: "{{xss_validator_directory}}/burp-extender"
    xss_validator_lib_directory: "{{xss_validator_extender_directory}}/lib"
    xss_validator_bin_directory: "{{xss_validator_extender_directory}}/bin/burp"
    xss_validator_deps:
      - http://central.maven.org/maven2/commons-codec/commons-codec/1.6/commons-codec-1.6.jar
      - http://central.maven.org/maven2/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar
      - http://central.maven.org/maven2/org/apache/httpcomponents/fluent-hc/4.3.6/fluent-hc-4.3.6.jar
      - http://central.maven.org/maven2/org/apache/httpcomponents/httpclient/4.3.6/httpclient-4.3.6.jar
      - http://central.maven.org/maven2/org/apache/httpcomponents/httpclient-cache/4.3.6/httpclient-cache-4.3.6.jar
      - http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.3.3/httpcore-4.3.3.jar
      - http://central.maven.org/maven2/org/apache/httpcomponents/httpmime/4.3.6/httpmime-4.3.6.jar
    co2_version: "1.1.11"

  tasks:
    - name: Install brew dependencies
      homebrew: name={{item}} state=latest update_homebrew=yes
      with_items: "{{brew_deps}}"

    - name: Create extensions directory
      file:
        path: "{{extension_directory}}"
        state: directory

    - name: Clone HUNT extension
      git:
        repo: git://github.com/bugcrowdlabs/HUNT.git
        dest: "{{extension_directory}}/HUNT"

    - name: Move the HUNT methodology into the extensions directory
      copy:
        src: "{{extension_directory}}/HUNT/hunt_methodology.py"
        dest: "{{extension_directory}}/hunt_methodology.py"

    - name: Move the HUNT scanner into the extensions directory
      copy:
        src: "{{extension_directory}}/HUNT/hunt_scanner.py"
        dest: "{{extension_directory}}/hunt_scanner.py"

    - name: Clean up HUNT directory
      file:
        state: absent
        path: "{{extension_directory}}/HUNT"

    - name: Retire.js extension
      get_url:
        url: https://raw.githubusercontent.com/h3xstream/burp-retire-js/gh-pages/releases/burp/burp-retire-js-3.jar
        dest: "{{extension_directory}}/burp-retire-js.jar"

    - name: Get jython standalone jar
      get_url:
        url: "http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/{{jython_version}}/jython-standalone-{{jython_version}}.jar"
        dest: "{{extension_directory}}/jython-standalone-{{jython_version}}.jar"

    - name: Clone xss validator
      git:
        repo: git://github.com/nVisium/xssValidator.git
        dest: "{{xss_validator_directory}}"

    - name: Create xss validator libs folder
      file:
        path: "{{xss_validator_lib_directory}}"
        state: directory

    - name: Download xss validator libs
      get_url: url={{item}} dest={{xss_validator_lib_directory}}
      with_items: "{{xss_validator_deps}}"

    - name: Build the jar
      shell: ant
      args:
        chdir: "{{xss_validator_bin_directory}}"

    - name: Move the jar into place
      copy:
        src: "{{xss_validator_bin_directory}}/xssValidator.jar"
        dest: "{{extension_directory}}/xssValidator.jar"

    - name: Clean up xss validator directory
      file:
        state: absent
        path: "{{xss_validator_directory}}"

    - name: Install CO2 extension
      get_url:
        url: "https://github.com/JGillam/burp-co2/releases/download/v{{co2_version}}/BurpCO2Suite.jar"
        dest: "{{extension_directory}}/BurpCO2Suite.jar"
