---
- name: Install Burp Extensions
  hosts: all

  roles:
    - co2
    #- xss_validator
    - common
    - retire_js
    - hunt
    - paramalyzer
    - csrf_scanner
    - content_type_converter
    - logger++
    - activescan++
    - backslash_powered_scanner
    - j2ee_scan
    - authmatrix
    - upload_scanner
    - copy_as_python_requests
    - json_web_tokens
    - freddy_deserialization_bug_finder
