---
- name: Install Burp Extensions
  hosts: all
  vars:
    logrotate_scripts:
      - name: ansible
        path: "/var/log/{{ ansible_user_id }}/ansible.log"
        options:
          - daily
          - missingok
          - rotate 7
          - maxage 7
          - dateext
          - dateyesterday

  roles:
    - common
    - co2
    - collaborator_everywhere
    - retire_js
    - hunt
    - http_request_smuggler
    - paramalyzer
    - content_type_converter
    - logger++
    - activescan++
    - backslash_powered_scanner
    - j2ee_scan
    - authmatrix
    - upload_scanner
    - copy_as_python_requests
    - json_web_tokens
    - freddy_deserialization_bug_finder
    - espresso
    - saml_raider
    - autorize
    - gen_user_options
    - gen_project_options
