---
- name: Install Burp Extensions
  hosts: all
  vars:
    logrotate_scripts:
      - name: "Configure logrotate with the log file"
        path: "{{ log_path }}/burp_extensions.log"
        options:
          - daily
          - missingok
          - rotate 7
          - maxage 7
          - dateext
          - dateyesterday

  roles:
    - common
    - activescan++
    - autorize
    - backslash_powered_scanner
    - co2
    - content_type_converter
    - copy_as_python_requests
    - collaborator_everywhere
    - espresso
    - freddy_deserialization_bug_finder
    - graphql_raider
    - http_request_smuggler
    - hunt
    - j2ee_scan
    - json_web_tokens
    - logger++
    - paramalyzer
    - retire_js
    - saml_raider
    - upload_scanner
    - gen_user_options
    - gen_project_options
