---
- name: Install Burp Extensions
  hosts: all

  roles:
    - common
    - co2
    - content_type_converter
    - csrf_scanner
    - hunt
    - paramalyzer
    - retire_js
    - xss_validator
    - logger++
