- name: Generate Burp User Options from template
  ansible.builtin.template:
    src: "{{ ansible_workspace }}/templates/burp_user_options.json.tmpl"
    dest: "{{ extension_dir }}/burp_user_options.json"
    mode: "0755"
