---
- name: Download bapp
  ansible.builtin.get_url:
    url: "{{ bapp_link }}"
    dest: "{{ bapp_file }}"
    mode: "0755"

- name: Create directory for bapp
  ansible.builtin.file:
    path: "{{ unzip_dir }}"
    state: directory
    mode: "0755"

- name: Unarchive bapp
  ansible.builtin.unarchive:
    src: "{{ bapp_file }}"
    dest: "{{ unzip_dir }}"

- name: Clean up bapp
  ansible.builtin.file:
    state: absent
    path: "{{ bapp_file }}"

- name: Find path to jar file
  ansible.builtin.find:
    paths: "{{ unzip_dir }}"
    patterns: "*.jar"
    recurse: "yes"
    file_type: "file"
  register: path

- name: Create fact to reference path in other roles
  ansible.builtin.set_fact: http_request_smuggler_path="{{ path.files.0.path }}"
