---
- name: Create extensions directory
  file:
   path: "{{extension_dir}}"
   state: directory

- name: Create dependencies directory
  file:
   path: "{{dep_dir}}"
   state: directory

- name: Get jython standalone jar
  get_url:
   url: "http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/{{jython_version}}/jython-standalone-{{jython_version}}.jar"
   dest: "{{dep_dir}}/jython-standalone-{{jython_version}}.jar"

- name: Keep burp extensions up-to-date
  cron:
   name: "Wipe and reload the burpExtensions directory at 16:00 every day"
   minute: '0'
   hour: "16"
   job: "mv {{extension_dir}} {{extension_dir}}.bak && {{ansible_playbook_bin}} {{ansible_workspace}}/site.yml -vvv && if [[ -d {{extension_dir}} ]]; then rm -rf {{extension_dir}}.bak; else cp -r {{extension_dir}}.bak {{extension_dir}}; fi"
  when: destroy_rebuild
