---
- name: Create extensions directory
  file:
    path: "{{ extension_dir }}"
    state: directory

- name: Create dependencies directory
  file:
    path: "{{ dep_dir }}"
    state: directory

- name: Get jython standalone jar
  get_url:
    url: "http://search.maven.org/remotecontent?filepath=org/python/jython-standalone/{{ jython_version }}/jython-standalone-{{ jython_version }}.jar"
    dest: "{{ dep_dir }}/jython-standalone-{{ jython_version }}.jar"

- name: Move update script into place
  template:
    src: "{{ ansible_workspace }}/templates/update.sh.tmpl"
    dest: "{{ extension_dir }}/update.sh"

- name: Create logs directory
  file:
    path: "{{ log_path }}"
    state: directory

- name: Keep burp extensions up-to-date
  cron:
   name: "Wipe and reload the burp_extensions directory at 16:00 every day"
   minute: '0'
   hour: "16"
   job: "bash {{ extension_dir }}/update.sh >> {{ log_path }}/burp_extensions.log"
  when: destroy_rebuild
