---
- name: Clone HUNT extension
  git:
   repo: git://github.com/bugcrowdlabs/HUNT.git
   dest: "{{ extension_dir }}/HUNT"

- name: Find path to python methodology file
  find:
    paths: "{{ extension_dir }}/HUNT"
    patterns: "*methodology.py"
    recurse: "yes"
    file_type: "file"
  register: methodology_path

# Create fact so that this can be referenced later
- set_fact: hunt_methodology_path="{{ methodology_path.files.0.path }}"

- name: Find path to python scanner file
  find:
    paths: "{{ extension_dir }}/HUNT"
    patterns: "*scanner.py"
    recurse: "yes"
    file_type: "file"
  register: scanner_path

# Create fact so that this can be referenced later
- set_fact: hunt_scanner_path="{{ scanner_path.files.0.path }}"
